// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: sf/ethereum/indigo/trxhash.proto

package pbtrxhash

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_ethereum_indigo_trxhash_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_indigo_trxhash_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_indigo_trxhash_proto_rawDescGZIP(), []int{0}
}

// A Transaction not yet in block
type TransactionHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash     []byte `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	PeerId     uint64 `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	BatchSize  uint64 `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	ReceivedAt uint64 `protobuf:"varint,4,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
}

func (x *TransactionHash) Reset() {
	*x = TransactionHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_ethereum_indigo_trxhash_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionHash) ProtoMessage() {}

func (x *TransactionHash) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_indigo_trxhash_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionHash.ProtoReflect.Descriptor instead.
func (*TransactionHash) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_indigo_trxhash_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionHash) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *TransactionHash) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TransactionHash) GetBatchSize() uint64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *TransactionHash) GetReceivedAt() uint64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

var File_sf_ethereum_indigo_trxhash_proto protoreflect.FileDescriptor

var file_sf_ethereum_indigo_trxhash_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x66, 0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x69, 0x6e,
	0x64, 0x69, 0x67, 0x6f, 0x2f, 0x74, 0x72, 0x78, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x73, 0x66, 0x2e, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2e,
	0x69, 0x6e, 0x64, 0x69, 0x67, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x41, 0x74, 0x32, 0x69, 0x0a, 0x15, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x50, 0x0a, 0x06, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x1f,
	0x2e, 0x73, 0x66, 0x2e, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2e, 0x69, 0x6e, 0x64,
	0x69, 0x67, 0x6f, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x73, 0x66, 0x2e, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2e, 0x69, 0x6e,
	0x64, 0x69, 0x67, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x61, 0x73, 0x68, 0x30, 0x01, 0x42, 0x52, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x66, 0x61,
	0x73, 0x74, 0x2f, 0x66, 0x69, 0x72, 0x65, 0x68, 0x6f, 0x73, 0x65, 0x2d, 0x65, 0x74, 0x68, 0x65,
	0x72, 0x65, 0x75, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x66,
	0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x69, 0x6e, 0x64, 0x69, 0x67, 0x6f,
	0x3b, 0x70, 0x62, 0x74, 0x72, 0x78, 0x68, 0x61, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sf_ethereum_indigo_trxhash_proto_rawDescOnce sync.Once
	file_sf_ethereum_indigo_trxhash_proto_rawDescData = file_sf_ethereum_indigo_trxhash_proto_rawDesc
)

func file_sf_ethereum_indigo_trxhash_proto_rawDescGZIP() []byte {
	file_sf_ethereum_indigo_trxhash_proto_rawDescOnce.Do(func() {
		file_sf_ethereum_indigo_trxhash_proto_rawDescData = protoimpl.X.CompressGZIP(file_sf_ethereum_indigo_trxhash_proto_rawDescData)
	})
	return file_sf_ethereum_indigo_trxhash_proto_rawDescData
}

var file_sf_ethereum_indigo_trxhash_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sf_ethereum_indigo_trxhash_proto_goTypes = []interface{}{
	(*HashRequest)(nil),     // 0: sf.ethereum.indigo.HashRequest
	(*TransactionHash)(nil), // 1: sf.ethereum.indigo.TransactionHash
}
var file_sf_ethereum_indigo_trxhash_proto_depIdxs = []int32{
	0, // 0: sf.ethereum.indigo.TransactionHashStream.Hashes:input_type -> sf.ethereum.indigo.HashRequest
	1, // 1: sf.ethereum.indigo.TransactionHashStream.Hashes:output_type -> sf.ethereum.indigo.TransactionHash
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sf_ethereum_indigo_trxhash_proto_init() }
func file_sf_ethereum_indigo_trxhash_proto_init() {
	if File_sf_ethereum_indigo_trxhash_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sf_ethereum_indigo_trxhash_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_ethereum_indigo_trxhash_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sf_ethereum_indigo_trxhash_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sf_ethereum_indigo_trxhash_proto_goTypes,
		DependencyIndexes: file_sf_ethereum_indigo_trxhash_proto_depIdxs,
		MessageInfos:      file_sf_ethereum_indigo_trxhash_proto_msgTypes,
	}.Build()
	File_sf_ethereum_indigo_trxhash_proto = out.File
	file_sf_ethereum_indigo_trxhash_proto_rawDesc = nil
	file_sf_ethereum_indigo_trxhash_proto_goTypes = nil
	file_sf_ethereum_indigo_trxhash_proto_depIdxs = nil
}
